#!/bin/bash

echo -e "Starting Python VENV\n"

source ./venv/bin/activate

echo -e "Exporting Flask Variables\n"
export FLASK_APP=platzi-api
export FLASK_DEBUG=1
export MONGO_DB_URI=`./.get-db-uri`

echo -e "Running Flask\n"

flask run
